### ISSUE TITLE
Why can’t I find this sub graph on thegraph.com/explorer?

### ISSUE THREAD

**Issue by watersnake1** [aave/protocol-v2-subgraph#23]
There was a different sub graph that I was using, called protocol multy raw, that I understood to be the updated v2 sub graph version. However as of a few days ago it seems that this sub graph is no longer indexing data. I can't see any sub graphs on the site under this name; has it been deployed yet with the graph?

**Comment by kyzia551** [comment]
Hey @watersnake1 !

Thank you for pointing it out, looks like it's some bug with TheGrpah indexer itself, will fix it asap.

If you need the v1 data then you need to continue using this subgraph

**Comment by watersnake1** [comment]
Thank you very much! Appreciate the quick response.
