### ISSUE TITLE
Add Incentives Rates

### ISSUE THREAD

**Issue by jojoCoWorker** [aave/protocol-v2-subgraph#29]
I couldn't find this data into the proposed schemes, would it be possible to add Incentives Rates in MATIC for deposit and borrow please ?

**Comment by sendra** [comment]
@jojoCoWorker its not possible to have the rates calculated in the subgraph. 

What you could do is get the necessary info from the subgraph about the reserves, and pass it to [aave-js](https://github.com/aave/aave-js) lib to get the rates calculated. 

You would need to call this [method](https://github.com/aave/aave-js/blob/master/src/v2/computations-and-formatting.ts#L521)
and it will return the incentive rates:
```
aIncentivesAPY,
vIncentivesAPY,
sIncentivesAPY,
```

**Comment by sendra** [comment]
Closing issue as it has been inactive for half a year
