### ISSUE TITLE
https://github.com/aave/protocol-v2-subgraph#development should mention `mustache` tool is required

### ISSUE THREAD

**Issue by Huge** [aave/protocol-v2-subgraph#3]
I have compiled https://github.com/aave/protocol-v2 before so I'd expect I have all the tools set up or ideally they get installed during the `npm run prepare:all` step.
But well, we could say the same on `graph-cli` and `env-cmd" which would add quite some hustle to your setup...

**Comment by Huge** [comment]
Oh, I see, this means either `npm install` or `npm run dev-environment` should be recommended as the first step.

**Comment by sendra** [comment]
Updated the README to have the correct instructions, with ```npm i``` to install package dependencies

https://github.com/aave/protocol-v2-subgraph/pull/6/files?file-filters%5B%5D=.md
