### ISSUE TITLE
Event with signature 'WethSet(indexed address)' not present in ABI 'AaveOracle'.

### ISSUE THREAD

**Issue by chulavege1** [aave/protocol-v2-subgraph#40]
Hi, i try to run command 
`# run codegen
npm run subgraph:codegen`
And then give me error.

Failed to load subgraph from subgraph.yaml: Error in subgraph.yaml:
  Path: dataSources > 0 > eventHandlers > 2
  Event with signature 'WethSet(indexed address)' not present in ABI 'AaveOracle'.
  Available events:
  - AssetSourceUpdated(indexed address,indexed address)
  - BaseCurrencySet(indexed address,uint256)
  - FallbackOracleUpdated(indexed address)
  - OwnershipTransferred(indexed address,indexed address)
  
if i delete lines (41-42) in the file subgraph.yaml 
**event: WethSet(indexed address)
handler: handleWethSet**
          
Then the command works without errors
However, if further I try to enter -
`npm run deploy:self-hosted:kovan ||
  npm run deploy:self-hosted:mainnet` 
or `
npm run deploy:hosted:kovan ||
npm run deploy:hosted:mainnet`

But when you call this command, a new file is generated this bug strings
Any idea how can i fix that ?
...
OS Fedora 35

**Comment by zhou533** [comment]
it seems like the contract was updated and 'WethSet' isn't available anymore. https://github.com/aave/protocol-v2/commit/0e7bc49a372dacd18203cd71fafd20c7f6616446#diff-3eb91bbed0969b7a39be2c39095e2ed0edf70f570f9170e779b5ecfbd5ea5430

**Comment by Shelvak** [comment]
For anybody that hits this issue, you could reset history in the v2 submodule:
```bash
cd externals/protocol-v2
git reset --hard d460ab4e # the commit before the WethSet change
cd ../../
yarn submodule:compile-contracts
yarn prepare:subgraph
```
I could deploy the subgraph with this little change. Waiting now for graph sync, hope everything works :pray:

**Comment by chulavege1** [comment]
Thanks guys for support
Wish you luck! 💎
