### ISSUE TITLE
Indexing error

### ISSUE THREAD

**Issue by yabirgb** [aave/protocol-v2-subgraph#43]
Hello, this morning the subgraph had an error indexing. This issue happens both in the hosted service https://thegraph.com/hosted-service/subgraph/aave/protocol-v2 and the decentralized service https://thegraph.com/explorer/subgraph?id=0x0d69090672c1e5a94e9aedfbc59558d18a78e1d3-0&view=Overview

**Comment by sendra** [comment]
This issue is resolved, and mainnet hosted subgraph is synced again. Regarding the decentralized one, it was not deployed by Aave, so I wouldn't know how to signal that it needs to be reindexed.

Thx for the warning :) will close the issue as it is solved
