### ISSUE TITLE
UserTransaction entities can be overwritten

### ISSUE THREAD

**Issue by davekaj** [aave/protocol-v2-subgraph#47]
Entities that implement the `UserTransaction` entity can be overwritten. This is because they all use the transaction hash as the `ID`. If a smart contract does two of the same actions wrapped into a single transaction, such as `deposit` and then `deposit` again - they will both have the same ID. This is quite an edge case, but I would guess there are a few instances where this has happened. 

I believe this bug may have already been caught by the team, judging by this  `TODO` comment:

https://github.com/aave/protocol-v2-subgraph/blob/2f9516a1b642791f2f7685f0d1883b5c8ed126d1/schema.graphql#L208-L211

Implementing this TODO would allow this issue to be closed. 

I would also recommend setting the ID as the transaction hash, with the event log index, instead of the `blockNumber + block position`. You get to include the transaction hash, and with the event log index, it will always be unique. It can be done with the following code:

```
let id = event.transaction.hash.toString().concat("-").concat(event.transactionLogIndex.toString())
```

**Comment by Rburdett4** [comment]
Bumping this. Ideally this could be fixed with the above code, and would ensure that integrations (for example custom `multicall` integrations for yield aggregators) can be supported.

**Comment by defispartan** [comment]
Thanks for raising this issue, I'll try to push this change forward. 

@davekaj What's the difference `transactionLogIndex` and `logIndex`?

**Comment by davekaj** [comment]
I don't remember to be honest. My guess is they are either the same, or else one is the log index of the transaction, and the other is the log index of the entire block.

For example, this tx: https://etherscan.io/tx/0x9eefde18e5894425439e14b09239ad61eeaf3cb148ef3f4b8d92d25a931c9841#eventlog

Has three logs, but the green circles are labeled 4, 5 and 6. So I believe the `transactionLogIndex` would be 0, 1 and 2, and the `logIndex` would be 4, 5 and 6. 

Either way, they would both create a unique ID
