### ISSUE TITLE
Link to this repo instead of gitlab in the yaml definition

### ISSUE THREAD

**Issue by Huge** [aave/protocol-v2-subgraph#5]
https://github.com/aave/protocol-v2-subgraph/blob/f62cc64342a71a6f387b89ba18b598e9f3063621/subgraph.template.yaml#L3 should be https://github.com/aave/protocol-v2-subgraph/ to confuse less people/developers.

**Comment by sendra** [comment]
updated template with the correct github repo, thx :)

here is the pr:
https://github.com/aave/protocol-v2-subgraph/pull/6/files?file-filters%5B%5D=.md
